title: jekyll-rtd-theme
lang: en
description: GitHub-flavored docs theme for Jekyll

theme: null

nav_version: true
edit: true
addons_branch: true

addons:
  - github
  - i18n
  - plugins
  - analytics

debug:
  compress: false

copyright:
  revision: true

readme_index:
  with_frontmatter: true

sass:
  style: compressed
  load_paths:
    - node_modules
    - node_modules/bourbon-neat/app/assets/stylesheets

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-octicons

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - jekyll-rtd-theme.gemspec
